# Generated by Django 3.2.15 on 2023-03-04 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('mobile', models.CharField(max_length=11)),
                ('address', models.CharField(max_length=50)),
                ('course', models.CharField(max_length=20)),
                ('edt', models.DateField()),
                ('remarks', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainer_name', models.CharField(max_length=20)),
                ('languages', models.CharField(max_length=30)),
                ('sal', models.IntegerField()),
                ('joined_date', models.DateField()),
                ('time', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='JoinedStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_date', models.DateField()),
                ('total', models.IntegerField()),
                ('first_ins', models.IntegerField()),
                ('first_date', models.DateField()),
                ('last_ins', models.IntegerField()),
                ('last_date', models.DateField()),
                ('duration', models.CharField(max_length=20)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.student')),
            ],
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('trainer', models.CharField(max_length=20)),
                ('bname', models.CharField(max_length=20)),
                ('students', models.ManyToManyField(to='home.Student')),
            ],
        ),
    ]
