# Generated by Django 3.2.15 on 2023-03-18 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_joinedstudent_dues'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.trainer'),
        ),
    ]
