# Generated by Django 3.2.15 on 2023-03-18 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_batch_trainer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='students',
            field=models.ManyToManyField(to='home.JoinedStudent'),
        ),
    ]
